spring:
  application:
    name: MaraTangOrderSystem
  config:
    import: "application-secret.yml"
  datasource:
    url: jdbc:mysql://13.124.165.57:3306/mara_tang_order?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true